on:
  pull_request:
  push:
    branches: "main"
name: "Gradle build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew -b ci.gradle package
